---
title: "Codebook"
author: "Andrey Ivanov"
date: "13.10.2019"
output:
  html_document:
    keep_md: yes
---

## Project Description
Study project of "Getting and Cleaning Data" course

##Description of the variables:
1. features  - data frame with names of features (file features.txt)
2. act_labels - data frame with names and labels of activities (file activity_labels.txt)
3. YTrain - data frame with labels of activities for train data (file Y_train.txt)
4. YTest - data frame with labels of activities for test data (file Y_test.txt)
5. SubjTrain - data frame with subject labels for train data (file subject_train.txt)
6. SubjTest - data frame with subject labels for test data (file subject_test.txt)
7. XTrain - data frame with features for train data (file X_train.txt)
8. XTest - data frame with features for test data (file X_test.txt)

9.  df - data frame fo collecting tidying all necessary data
10. fMeanStd - vector to collect feature names of "mean" and "std" data
11. activities - data frame to store activity names for all measures


